export const defaultTypeEs = {
    'ghost': 'Fantasma',
    'dark': 'Siniestro',
    'electric': 'Eléctrico',
    'normal': 'Normal',
    'fire': 'Fuego',
    'psychic': 'Psíquico',
    'flying': 'Volador',
    'steel': 'Acero',
    'poison': 'Veneno',
    'dragon': 'Dragón',
    "water": 'Agua',
    'ice': 'Hielo',
    'rock': 'Roca',
    'fighting': 'Lucha',
    'grass': 'Planta',
    'bug': 'Bicho',
    'ground': 'Tierra',
    'fairy': 'Hada',
}